name: psana_env
channels:
 - lcls-i
 - conda-forge
 - cctbx
 - defaults
dependencies:
 # conda compilers
 - c-compiler
 - cxx-compiler
 - scons

 # psana
 - psana

 # python
 - python
 - biopython
 - ipython

 # testing
 - pytest
 - pytest-xdist

 # documentation
 - docutils
 - numpydoc
 - sphinx

 # graphics
 - pillow
 - reportlab
 - wxpython
 - pyopengl

 # HDF5 (main libraries come with psana)
 # 11/08/22: pin h5py, see h5py/h5py#1880 and conda-forge/h5py-feedstock#92
 - h5py<3.2
 - hdf5plugin  # [unix]

 # other
 - libsvm
 - mrcfile
 - psutil
 - mpi4py
 - pandas
 - pybind11
 - setuptools

 # cctbx channel
 - libsvm_py

 # dials
 - jinja2
 - msgpack-python
 - orderedset
 - procrunner
 - python-blosc
 - scikit-learn
 - tqdm
 - eigen
 - dials-data
 - pint

 # xia2
 - tabulate

 # Phenix
 - send2trash
 - PyRTF

 # xfel gui
 - mysql
 - mysqlclient

 # Avoid numpy 1.21.[01234]
 # See https://github.com/cctbx/cctbx_project/issues/627
 - numpy=1.20|>=1.21.5
