# Weekly builds to run slow tests

# no continuous integration builds or pull requests
trigger: none
pr: none

# only weekly builds on Friday Pacific
schedules:
- cron: '0 5 * * 6'
  displayName: Weekly build
  branches:
    include:
    - master

resources:
  pipelines:
  - pipeline: data_cache
    source: 'Update data cache'
  - pipeline: build_cache
    source: 'Update build cache'

stages:
- stage: Preparation
  displayName: Download
  jobs:
    - template: ./download-source.yml

- stage: Build
  displayName: Build and test
  dependsOn: Preparation
  jobs:
    - template: ./xfel-ci-build.yml
      parameters:
        slow_tests: True
