# Templates for linux, macOS, and Windows
# Based on approach from conda-forge

stages:
- stage: Preparation
  displayName: Download
  jobs:
    - template: ./download-source.yml

- stage: Build
  displayName: Build and test
  dependsOn: Preparation
  jobs:
    - template: ./conda-linux.yml
      parameters:
        distribution: centos
        version: [6]
    - template: ./conda-psana.yml
      parameters:
        distribution: centos
        version: [7]
    - template: ./conda-osx.yml
      parameters:
        vmImage: [10, 14]
        xcode_version: [11, 3, 1]
