# Script for building CCTBX
# linux image descriptions
# https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/linux/Ubuntu1604-README.md

jobs:
- job: ${{ format('{0}_{1}', parameters.distribution, join('_', parameters.version) ) }}
  pool:
    vmImage: ubuntu-latest
  timeoutInMinutes: 360
  strategy:
    maxParallel: 3
    matrix:
      python2.7:
        CONDA: Linux
        OS: linux-64
        PYTHON_VERSION: py27
  container:
    image: ${{ parameters.distribution }}:${{ join('.', parameters.version) }}
    options: "--name ci-container -v /usr/bin/docker:/tmp/docker:ro"

  steps:
  # https://github.com/ApexAI/performance_test/blob/master/azure-pipelines.yml#L9-L17

  # centos setup
  - script: |
      /tmp/docker exec -t -u 0 ci-container \
      sh -c "yum install -y sudo"
    displayName: Set up sudo for CentOS
    condition: eq('${{ parameters.distribution }}', 'centos')

  - script: |
      sudo yum groupinstall -y 'Development Tools'
      sudo yum install -y mesa-libGLU-devel mesa-libGL-devel tcsh
    displayName: Install dependencies for CentOS
    condition: eq('${{ parameters.distribution }}', 'centos')

  # build
  - template: ./unix-psana-build.yml
