# Daily update of conda package artifacts

# no continuous integration builds or pull requests
trigger: none
pr: none

# daily updates
schedules:
- cron: '0 0 * * *'
  displayName: Daily update of conda packages
  branches:
    include:
    - master

stages:
- stage: Preparation
  displayName: Download
  jobs:
    - template: ./download-conda.yml
