# Nightly builds

# no continuous integration builds
trigger: none

# only nightly and pull request builds
schedules:
- cron: '0 1 * * *'
  displayName: Nightly build
  branches:
    include:
    - master

stages:
- stage: Preparation
  displayName: Download
  jobs:
    - template: ./download-source.yml
    - template: ./download-conda.yml

- stage: Build
  displayName: Build and test
  dependsOn: Preparation
  jobs:
    - template: ./full-build.yml
      parameters:
        modules: modules
