# Templates for linux, macOS, and Windows
# Based on approach from conda-forge

# skip pull requests
pr: none

# batch builds for branches
trigger:
  batch: true
  branches:
    exclude:
      - master

stages:
- stage: Preparation
  displayName: Download
  jobs:
    - template: ./.azure-pipelines/download-source.yml

- stage: Build
  displayName: Build and test
  dependsOn: Preparation
  jobs:
    - template: ./.azure-pipelines/ci-build.yml
      parameters:
        modules: modules
