# Full conda builds

# no continuous integration builds
trigger: none

stages:
- stage: Preparation
  displayName: Download
  jobs:
    - template: ./download-source.yml
    - template: ./download-conda.yml

- stage: Build
  displayName: Build and test
  dependsOn: Preparation
  jobs:
    - template: ./full-build.yml
      parameters:
        modules: modules
