# Weekly update of build cache artifacts

# no continuous integration builds or pull requests
trigger: none
pr: none

# weekly builds on Saturday Pacific
schedules:
- cron: '0 5 * * 0'
  displayName: Weekly rebuild of cache artifacts
  branches:
    include:
    - master

stages:
- stage: Preparation
  displayName: Download
  jobs:
    - template: ./download-source.yml

- stage: Build
  displayName: Build and test
  dependsOn: Preparation
  jobs:
    - template: ./full-build.yml
      parameters:
        modules: modules
