# Script for installing miniconda and conda environment
#
# The source must have already been checked out
#
# Variables:
#   CONDA: Linux, MacOSX
#   PYTHON_VERSION: py27, py36
#   OS: linux-64, osx-64

steps:

- script: |
    echo "Installing Miniconda"
    set -x -e
    curl -o $(Build.StagingDirectory)/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-$(CONDA)-x86_64.sh
    bash $(Build.StagingDirectory)/miniconda.sh -b -u -p $(Build.StagingDirectory)/miniconda
    export PATH=$(Build.StagingDirectory)/miniconda/bin:$PATH
    echo "Setting up Conda environment"
  displayName: Install miniconda

- script: |
    source $(Build.StagingDirectory)/miniconda/etc/profile.d/conda.sh
    conda create -y -n $(PYTHON_VERSION) --file ./libtbx/auto_build/conda_envs/cctbx_$(PYTHON_VERSION)_$(OS).txt
    conda install -y -c conda-forge --no-deps -n $(PYTHON_VERSION) junit-xml
  displayName: Create conda environment
