# Test current conda packages on the conda-forge and cctbx-nightly
# channels. This is for testing for any breaking changes in the
# dependencies.
#
# macos-13 will test the x86-64 packages
# macos-14 will test the Apple Silicon packages

name: Nightly conda package tests
on: workflow_dispatch
  # schedule:
  #   - cron: '0 5 * * *'

jobs:
  test_conda_packages:
    if: github.repository == 'cctbx/cctbx_project'

    strategy:
      matrix:
        channel: [conda-forge, cctbx-nightly]
        os: [ubuntu-latest, macos-14, macos-13, windows-latest]
        python_version: [3.8, 3.9, 3.10, 3.11, 3.12]

    name: Testing (${{ channel }} ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python_version }}
          activate-environment: test
      - name: Environment info
        run: |
          conda info
          conda list
